### ISSUE TITLE
mup setup error "Error loading config file" when  run in root dir, or Micro JScript error when run in .deploy dir

### ISSUE THREAD

**Issue by dsten32** [zodern/meteor-up#1186]
Mup version (`mup --version`): 1.5.1

Mup config

```js
Error loading config file:
Error: Cannot find module 'C:\Users\******\VScode\Repositories\juryroom\mup.js'
Require stack:
- C:\Users\******\AppData\Roaming\npm\node_modules\mup\lib\plugin-api.js
- C:\Users\******\AppData\Roaming\npm\node_modules\mup\lib\index.js
- C:\Users\******\AppData\Roaming\npm\node_modules\mup\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
    at PluginAPI.getConfig (C:\Users\******\AppData\Roaming\npm\node_modules\mup\lib\plugin-api.js:257:38)
    at Object.setup [as handler] (C:\Users\******\AppData\Roaming\npm\node_modules\mup\lib\plugins\docker\command-handlers.js:53:22)
    at PluginAPI.runCommand (C:\Users\******\AppData\Roaming\npm\node_modules\mup\lib\plugin-api.js:135:40)
    at async PluginAPI.runCommand (C:\Users\******\AppData\Roaming\npm\node_modules\mup\lib\plugin-api.js:135:9) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\******\\AppData\\Roaming\\npm\\node_modules\\mup\\lib\\plugin-api.js',
    'C:\\Users\\******\\AppData\\Roaming\\npm\\node_modules\\mup\\lib\\index.js',
    'C:\\Users\\******\\AppData\\Roaming\\npm\\node_modules\\mup\\index.js'
  ]
}

```

Output of command

```bash
Error loading config file:
Error: Cannot find module 'C:\Users\******\VScode\Repositories\juryroom\mup.js'
Require stack:
- C:\Users\******\AppData\Roaming\npm\node_modules\mup\lib\plugin-api.js
- C:\Users\******\AppData\Roaming\npm\node_modules\mup\lib\index.js
- C:\Users\******\AppData\Roaming\npm\node_modules\mup\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
    at PluginAPI.getConfig (C:\Users\******\AppData\Roaming\npm\node_modules\mup\lib\plugin-api.js:257:38)
    at Object.setup [as handler] (C:\Users\******\AppData\Roaming\npm\node_modules\mup\lib\plugins\docker\command-handlers.js:53:22)
    at PluginAPI.runCommand (C:\Users\******\AppData\Roaming\npm\node_modules\mup\lib\plugin-api.js:135:40)
    at async PluginAPI.runCommand (C:\Users\******\AppData\Roaming\npm\node_modules\mup\lib\plugin-api.js:135:9) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\******\\AppData\\Roaming\\npm\\node_modules\\mup\\lib\\plugin-api.js',
    'C:\\Users\\******\\AppData\\Roaming\\npm\\node_modules\\mup\\lib\\index.js',
    'C:\\Users\\******\\AppData\\Roaming\\npm\\node_modules\\mup\\index.js'
  ]
}

```

if running mup setup in the .deply dir the following error is seen:
```
---------------------------
Windows Script Host
---------------------------
Script:	C:\Users\*****\VScode\Repositories\juryroom\.deploy\mup.js
Line:	20
Char:	5
Error:	Expected identifier, string or number
Code:	800A0404
Source: 	Microsoft JScript compilation error

---------------------------
OK   
---------------------------
```

content of mup.js:
```
module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: '*****',
      username: '*****',
      pem: '*****'
      // password: 'server-password'
      // or neither for authenticate from ssh-agent
    }
  },

  app: {
    // TODO: change app name and path
    name: '*****',
    path: '../',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: 'http://*****.australiasoutheast.cloudapp.azure.com',
      MONGO_URL: '*****',
      MONGO_OPLOG_URL: 'mongodb://mongodb/local',
    },

    docker: {
      // abernix/meteord:node-12-base works with Meteor 1.9 - 1.10
      // If you are using a different version of Meteor,
      // refer to the docs for the correct image to use.
      image: 'abernix/meteord:node-12-base',
    },

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },

  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  },

  // (Optional)
  // Use the proxy to setup ssl or to route requests to the correct
  // app when there are several apps

  // proxy: {
  //   domains: 'mywebsite.com,www.mywebsite.com',

  //   ssl: {
  //     // Enable Let's Encrypt
  //     letsEncryptEmail: 'email@domain.com'
  //   }
  // }
};


```

**Comment by zodern** [comment]
If you are using the command prompt, you must run `mup.cmd` instead of `mup`. Otherwise, Windows will try to run the `mup.js` file. Powershell works correctly.
