### ISSUE TITLE
Mup deploy success but app doesn't open 

### ISSUE THREAD

**Issue by xpressabhi** [zodern/meteor-up#777]
I have updated my app to Meteor 1.6 today, mup deploy shows success but while accessing the app from browser I see bad gateway message.

Mup logs return this..
[serverip]=> Starting meteor app on port:80
[serverip]/built_app/programs/server/boot.js:50
[serverip]    const { pause } = require("./debug.js");
[serverip]          ^
[serverip]
[serverip]SyntaxError: Unexpected token {
[serverip]    at exports.runInThisContext (vm.js:53:16)
[serverip]    at Module._compile (module.js:373:25)
[serverip]    at Object.Module._extensions..js (module.js:416:10)
[serverip]    at Module.load (module.js:343:32)
[serverip]    at Function.Module._load (module.js:300:12)
[serverip]    at Module.require (module.js:353:17)
[serverip]    at require (internal/module.js:12:17)
[serverip]    at Object.<anonymous> (/built_app/main.js:4:1)
[serverip]    at Module._compile (module.js:409:26)
[serverip]    at Object.Module._extensions..js (module.js:416:10)
[serverip]=> Starting meteor app on port:80
[serverip]/built_app/programs/server/boot.js:50
[serverip]    const { pause } = require("./debug.js");
[serverip]          ^
[serverip]

I have reverted my changes then deployed again, it works perfectly with Meteor 1.5.2.2.
I will sit at 1.5.2.2 till this issue resolved.

**Comment by html5-ninja** [comment]
same

**Comment by dominicarrojado** [comment]
Same here as well.

**Comment by timbrandin** [comment]
I have the same issue.

**Comment by ziedmahdi** [comment]
does changing the docker image resolve your problem?
[use abernix/meteord:node-8.4.0-base](https://github.com/zodern/meteor-up/issues/748#issuecomment-333159380)

**Comment by Elviron** [comment]
@ziedmahdi It works for me, haven't noticed any problems yet!

**Comment by evuori** [comment]
Same "Bad Gateway 502" error here on 80/443. 

Found few similar past issues relating ssl config but getting error with or without force-ssl package.

**Comment by zodern** [comment]
@evuori what does `mup docker ps` show? Does `mup logs --tail 100` show any errors?

**Comment by evuori** [comment]
@zodern sorry can't reproduce since I had to roll back to 1.5.2. However,  I am setting up fresh instance at the moment so will have chance to try in few hours...

**Comment by evuori** [comment]
ok, hands dirty here. Found nothing special, logs pretty much same as @xpressabhi.
Only difference is that im getting "Could Not Connect" response instead. 

```
$mup deploy
Started TaskList: Pushing Meteor App
[xx.xxx.xxx.xx] - Pushing Meteor App Bundle to The Server
[xx.xxx.xxx.xx] - Pushing Meteor App Bundle to The Server: SUCCESS
[xx.xxx.xxx.xx] - Prepare Bundle
[xx.xxx.xxx.xx] - Prepare Bundle: SUCCESS

Started TaskList: Configuring App
[xx.xxx.xxx.xx] - Pushing the Startup Script
[xx.xxx.xxx.xx] - Pushing the Startup Script: SUCCESS
[xx.xxx.xxx.xx] - Sending Environment Variables
[xx.xxx.xxx.xx] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[xx.xxx.xxx.xx] - Start Meteor
[xx.xxx.xxx.xx] - Start Meteor: SUCCESS
[xx.xxx.xxx.xx] - Verifying Deployment
[xx.xxx.xxx.xx] x Verifying Deployment: FAILED

$mup logs --tail=100
[xx.xxx.xxx.xx]SyntaxError: Unexpected token {
[xx.xxx.xxx.xx]    at exports.runInThisContext (vm.js:53:16)
[xx.xxx.xxx.xx]    at Module._compile (module.js:373:25)
[xx.xxx.xxx.xx]    at Object.Module._extensions..js (module.js:416:10)
[xx.xxx.xxx.xx]    at Module.load (module.js:343:32)
[xx.xxx.xxx.xx]    at Function.Module._load (module.js:300:12)
[xx.xxx.xxx.xx]    at Module.require (module.js:353:17)
[xx.xxx.xxx.xx]    at require (internal/module.js:12:17)
[xx.xxx.xxx.xx]   at Object.<anonymous> (/built_app/main.js:4:1)
[xx.xxx.xxx.xx]    at Module._compile (module.js:409:26)
[xx.xxx.xxx.xx]    at Object.Module._extensions..js (module.js:416:10)
[xx.xxx.xxx.xx]=> Starting meteor app on port:80
[xx.xxx.xxx.xx]/built_app/programs/server/boot.js:50
[xx.xxx.xxx.xx]    const { pause } = require("./debug.js");
```

Should `docker ps` show 80/443 in container PORT?

* update: removed addressinfo

**Comment by evuori** [comment]
With "abernix/meteord:node-8.4.0-base" things working good in Meteor 1.6, no issues, confirmed.

**Comment by xpressabhi** [comment]
Image abernix/meteord:node-8.4.0-base works with meteor 1.6, hope it syncs to meteor node 8.8.1 version soon.

**Comment by crstn210** [comment]
@zodern  I'm expecting the same issue, meteor 1.6,  abernix/meteord:node-8.4.0-base

mup.cmd logs --tail 100 : 
[]    at Module.load (module.js:507:32)
[]    at tryModuleLoad (module.js:470:12)
[]    at Function.Module._load (module.js:462:3)
[]=> Starting meteor app on port:80
[]/built_app/programs/server/node_modules/fibers/future.js:280
[]                                           throw(ex);
[]                                           ^
[]
[]Error: Cannot find module 'bl'
[]    at Function.Module._resolveFilename (module.js:489:15)
[]    at Function.Module._load (module.js:439:25)
[]    at Module.require (module.js:517:17)
[]    at require (internal/module.js:11:18)
[]    at Object.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/dfischer_prerenderio/node_modules/prerender-node/node_modules/request/request.js:9:10)
[]    at Module._compile (module.js:573:30)
[]    at Object.Module._extensions..js (module.js:584:10)
[]    at Module.load (module.js:507:32)
[]    at tryModuleLoad (module.js:470:12)
[]    at Function.Module._load (module.js:462:3)
[]=> Starting meteor app on port:80

**Comment by tanermelikoglu** [comment]
i have the same issue, with Meteor 1.6.0.1, abernix/meteord:node-8.4.0-base, node v8.9.3, mup 1.3.7 at deploying the app on digital ocean

**Comment by crstn210** [comment]
any ideas how to solve this?

**Comment by tanermelikoglu** [comment]
In my case the deployment failed at verifying stage on digital ocean. 

Docker image is pushed without any tag and version, so the container can't found the  image with given name and tag (myapp:latest) and shut down.

I found in other forum, that not valid settings.json (in public area) causes the problem. The solution would be deploy the app with empty settings.json. ( {} ) But it does not work for me. 

I don't know the real reason of the problem. I deployed my app many times with meteor 1.4.x and node 4.x. Now i updated all the packages,  mup, node and the docker image but nothing helps.

**Comment by myktra** [comment]
**UPDATE: Solved.**

**My forked Docker image [myktra/meteord:base](https://hub.docker.com/r/myktra/meteord/) was not automatically published to Docker Hub for some reason. So the older fork I was trying to replace continued to run with Node 4.8.x, and was thus incompatible with Meteor 1.6. So keep an eye on your Docker images and make sure MUP is deploying the right base image for Meteor.**

--

I'm running into this issue as well upgrading a Meteor 1.5.4.x/Node 4.8.x application. I maintain a fork of abernix/meteord:base for the sole purpose of passing options to Node to run in a low-memory environment. When I updated my fork with the latest improvements (Node 8.9.3, etc.), and use mup 1.3.7 I receive similar deployment errors.

FWIW, my host machine is an Ubuntu 14.04.5 LTS.

```
.
.
.
{
  "meteor-dev-bundle": "0.0.0",
  "npm": "4.6.1",
  "ares": "1.10.1-DEV",
  "http_parser": "2.7.0",
  "icu": "56.1",
  "modules": "46",
  "node": "4.8.4",
  "openssl": "1.0.2k",
  "uv": "1.9.1",
  "v8": "4.5.103.47",
  "zlib": "1.2.11"
}
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
=> Starting meteor app on port:80
/bundle/bundle/programs/server/boot.js:50
    const { pause } = require("./debug.js");
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
.
.
.
```
